# Generated by Django 4.1.7 on 2023-02-16 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditSearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_term', models.CharField(max_length=200)),
                ('date_searched', models.DateField(verbose_name='Date Searched')),
            ],
        ),
        migrations.CreateModel(
            name='RedditSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
                ('subreddit', models.CharField(max_length=30)),
                ('upvotes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('search_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraperUI.redditsearchterm')),
            ],
        ),
    ]
