# Generated by Django 4.1.7 on 2023-02-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditsearchterm',
            name='date_searched',
            field=models.DateTimeField(verbose_name='Date Searched'),
        ),
    ]
